name: Echo Secrets and Variables
on:
  push:
    branches:
      - main  # Trigger this action when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_VARIABLE: "This is not a secret"  # This is a public environment variable
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Echo environment variable1
        run: echo "My environment variable defined in workflow is $MY_VARIABLE" # not be masked
      - name: Echo environment variable2
        run: echo "My environment variable defined in repo settings is $MY_REPO_VAR" # not be masked
      - name: Echo fake secret
        run: echo "My fake secret is ${{ secrets.MY_FAKE_SECRET }}" # masked